apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: d-4
  labels:
    type: bule-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: myapp 
      replica: blue
  template: 
    metadata: 
      labels: 
        app: myapp
        replica: blue             # labels shoud match with service.yml and based on labels send traffic blue to green and green to blue 
    spec: 
      containers:
        - name: c-4
          image: nginx
          ports:
            - name: http
              containerPort: 80