apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: myapp
spec:
  serviceAccountName: s3-access-sa
  containers:
  - name: awscli
    image: amazonlinux:2
    command: ["sleep", "3600"]

