apiVersion: apps/v1
kind: Deployment

metadata:
  name: d-6
  labels:
    app: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-demo                # all labels are same v-1, v-2 and service all labels are same 

  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: c-2
          image: httpd #version-2
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "150Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "400Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      
      