apiVersion: v1
kind: Service
metadata: 
  name: s-1
  labels: 
    type: canary
spec: 
  type: NodePort
  selector: 
    app: canary-demo           # all labels are same v-1, v-2 and service all labels are same 
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30008


  # in this method service send traffic both old version and new verrsion  so we can scale down v-1 and 
  # scale up v-2 slowly and converrt traffic at v-1 to v-2 without any application down or impact