apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-deployment 
  labels: 
    type: d-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: myapp
  template: 
    metadata:
      labels:
        app: myapp
        type: frontend-pod
    spec:
      containers:
        - name: c-1
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: s-1
  labels: 
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: myapp 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
