apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-deployment 
  labels: 
    type: d-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: myapp
  template: 
    metadata:
      labels:
        app: myapp
        type: frontend-pod
    spec:
      containers:
        - name: c-1
          image: httpd        ## if you want to use custom image then ; image : repository url : < image tag/name >  or , image : repository url @ digest 
                              ## ex :-   image : 451947743144.dkr.ecr.us-east-1.amazonaws.com/my-image:latest    or      , image : 451947743144.dkr.ecr.us-east-1.amazonaws.com/my-image@sha256:b22f8a31d499f51d48ae488184837ad2c2525f6d9dafa99c6ef05cc09ba02b29
                              ## image : url@digest    = this is safe way in this if image change  then no problem 
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: s-1
  labels: 
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: myapp 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


#### cluster ip service is for internal communicaton purpose used like pod to pod communication  for ex : frontend to backend and backend to db communication    ############
