apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi                 # this pv is usign node ebs volume if node delete then volume also delete and pod recreate in diffrent node then vlomes data are completly unsync .
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"