apiVersion: apps/v1
kind: Deployment              # only change in kind remaining all are as it replicaset .
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80 